version: '3'

services:
  pdf-llm-api:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - ./uploads:/app/uploads
      - ./vectorstores:/app/vectorstores
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5002
    restart: unless-stopped 