version: '3.8'

services:
  pdf-llm-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pdf-llm-api:latest
    container_name: pdf-llm-api
    expose:
      - "5002"
    volumes:
      - pdf_uploads:/app/uploads
      - pdf_vectorstores:/app/vectorstores
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5002
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    depends_on:
      - pdf-llm-api
    restart: unless-stopped
    networks:
      - app-network

  # Uncomment to add SSL with Let's Encrypt
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email -d api.yourdomain.com

volumes:
  pdf_uploads:
  pdf_vectorstores:

networks:
  app-network:
    driver: bridge 