version: '3.8'

services:
  pdf-llm-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pdf-llm-api:latest
    container_name: pdf-llm-api
    ports:
      - "5002:5002"
    volumes:
      - ./uploads:/app/uploads
      - ./vectorstores:/app/vectorstores
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5002
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 